### ISSUE TITLE
Onboarding client error

### ISSUE THREAD

**Issue by bobcatcoder** [helium/react-native-helium#40]
When onboarding, sometimes it crashed in the react-native-sdk with "Onboarding client error" but we don't know what's wrong with it. Can you please return detailed error and the reason from SDK?

```
Crashed in non-app: node_modules/@helium/react-native-sdk/src/Onboarding/useOnboarding.tsx in handleError
```

exception
Error: Onboarding client error
Error

```
device
   iPhone14,2
device.family
   iOS
level
   error
os
   iOS 15.2.1
os.name
   iOS
os.rooted
    no
```

```
Error: Onboarding client error
  at handleError(node_modules/@helium/react-native-sdk/src/Onboarding/useOnboarding.tsx:21:17)
  at call(node_modules/@helium/react-native-sdk/src/Onboarding/useOnboarding.tsx:48:7)
  at tryCatch(node_modules/regenerator-runtime/runtime.js:63:40)
  at call(node_modules/regenerator-runtime/runtime.js:293:22)
  at tryCatch(node_modules/regenerator-runtime/runtime.js:63:40)
  at invoke(node_modules/regenerator-runtime/runtime.js:154:20)
  at fn(node_modules/regenerator-runtime/runtime.js:164:13)
  at tryCallOne(node_modules/promise/setimmediate/core.js:37:12)
  at apply(node_modules/promise/setimmediate/core.js:123:15)
  at callback(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:248:18)
  at _callTimer(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:112:7)
  at _callReactNativeMicrotasksPass(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:166:5)
  at _reactNativeMicrotasksCallback(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:418:12)
  at __callReactNativeMicrotasks(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:393:12)
  at fn(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:12)
  at __guard(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:370:9)
  at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:10)
  at value([native code])
  at value([native code])
```

**Comment by tyler-whitman** [comment]
@bobcatcoder You found out that the onboarding server was responding with a 429 when trying to get a hotspots onboarding data.

I have a pull request to provide better fallback error messaging so that you will know which call has failed.
